-- TB PAYMENTS
CREATE TRIGGER TRG_SET_PAYMENT_APPROVED_AT ON TB_PAYMENTS
AFTER
UPDATE AS BEGIN
SET NOCOUNT ON
    UPDATE TB_PAYMENTS
SET PAYMENT_APPROVED_AT = GETDATE()
FROM TB_PAYMENTS P 
    INNER JOIN INSERTED I ON P.ID = I.ID
    INNER JOIN DELETED D ON D.ID = I.ID
WHERE I.PAYMENT_STATUS = 'approved'
    AND (
        D.PAYMENT_STATUS <> 'approved'
        OR D.PAYMENT_STATUS IS NULL
    );
END
GO