-- Views with TB_PAYMENTS
CREATE VIEW VW_PAYMENTS_FORMATTED_PORTUGUESE AS
SELECT
    ID,
    'R$ ' + REPLACE(FORMAT(VALUE_PAID, 'N2'), '.', ',') AS VALUE_PAID_FORMATTED,
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    PAYMENT_APPROVED_AT,
    REPLACE(FORMAT(TAX, 'N1'), '.', ',') + '%' AS TAX_FORMATTED,
    DISCOUNT,
    DISCOUNT_REASON,
    INSTALLMENT,
    'R$ ' + REPLACE(FORMAT(INSTALLMENT_AMOUNT, 'N2'), '.', ',') AS INSTALLMENT_AMOUNT_FORMATTED,
    CREATED_AT,
    UPDATED_AT
FROM TB_PAYMENTS