-- =================================================================
-- PROCEDURES PARA ATUALIZAR UPDATED_AT DE CADA TABELA
-- Use estas procedures em vez de triggers para atualizar o campo UPDATED_AT.
-- Basta chamar a procedure após um UPDATE real na aplicação ou em procedures do projeto.
-- =================================================================

--Como usar:

--Após um UPDATE em qualquer tabela, chame a procedure passando o ID do registro atualizado.
--Exemplo para TB_USERS:
--SQL
--UPDATE TB_USERS SET NAME = 'Novo Nome' WHERE ID = @ID
--EXEC SP_UPDATE_USERS_UPDATED_AT @ID

-- TB_USERS
CREATE OR ALTER PROCEDURE SP_UPDATE_USERS_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_USERS
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_RATINGS
CREATE OR ALTER PROCEDURE SP_UPDATE_RATINGS_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_RATINGS
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_MEDIAS
CREATE OR ALTER PROCEDURE SP_UPDATE_MEDIAS_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_MEDIAS
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_RESERVATIONS
CREATE OR ALTER PROCEDURE SP_UPDATE_RESERVATIONS_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_RESERVATIONS
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_PAYMENTS
CREATE OR ALTER PROCEDURE SP_UPDATE_PAYMENTS_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_PAYMENTS
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_TRAVELERS
CREATE OR ALTER PROCEDURE SP_UPDATE_TRAVELERS_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_TRAVELERS
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_PACKAGES
CREATE OR ALTER PROCEDURE SP_UPDATE_PACKAGES_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_PACKAGES
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO

-- TB_PACKAGES_DATES
CREATE OR ALTER PROCEDURE SP_UPDATE_PACKAGES_DATES_UPDATED_AT
    @ID UNIQUEIDENTIFIER
AS
BEGIN
    UPDATE TB_PACKAGES_DATES
    SET UPDATED_AT = GETDATE()
    WHERE ID = @ID;
END
GO