-- Constraints Usuários

ALTER TABLE TB_USERS
ADD CONSTRAINT CK_USERS_ROLE
CHECK (ROLE IN ('USER', 'ATENDENTE', 'ADMIN'));
GO

ALTER TABLE TB_USERS 
ADD CONSTRAINT CK_BIRTHDATE 
CHECK (BIRTHDATE <= DATEADD(YEAR, -18, GETDATE()));
GO

ALTER TABLE TB_USERS 
ADD CONSTRAINT CK_PHONE_FORMAT 
CHECK (PHONE LIKE '([0-9][0-9]) [0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]');
GO

ALTER TABLE TB_USERS 
ADD CONSTRAINT CK_EMAIL_FORMAT 
CHECK (EMAIL LIKE '%@%.com');
GO

ALTER TABLE TB_USERS 
ADD CONSTRAINT CK_DOCUMENT_FORMAT
CHECK ( 
        DOCUMENT LIKE '[0-9][0-9][0-9].[0-9][0-9][0-9].[0-9][0-9][0-9]-[0-9][0-9]' OR 
        DOCUMENT LIKE '[A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]'
);
GO

ALTER TABLE TB_USERS
ADD CONSTRAINT UNIQUE_USERS_EMAIL
UNIQUE (EMAIL);
GO

ALTER TABLE TB_USERS
ADD CONSTRAINT UNIQUE_USERS_DOCUMENT
UNIQUE (DOCUMENT);
GO

ALTER TABLE TB_USERS
ADD CONSTRAINT UNIQUE_USERS_PHONE
UNIQUE (PHONE);
GO

-- Constraints Reserva

ALTER TABLE TB_RESERVATIONS 
	ADD CONSTRAINT CHK_RESERVATIONS_SITUATION 
	CHECK (SITUATION IN ('pendente', 'confirmada', 'cancelada'))
GO

ALTER TABLE TB_RESERVATIONS
    ADD CONSTRAINT CHK_RESERVATION_DATE_FUTURE
    CHECK (RESERVATION_DATE >= CONVERT(date, GETDATE()))
GO

ALTER TABLE TB_RESERVATIONS
    ADD CONSTRAINT CHK_CANCEL_DATE_FUTURE
    CHECK (CANCEL_DATE IS NULL OR CANCEL_DATE >= CONVERT(date, GETDATE()))
GO

-- Constraints Pagamentos

ALTER TABLE TB_PAYMENTS
ADD CONSTRAINT CHK_PAYMENTS_STATUS CHECK (
        PAYMENT_STATUS IN ('aprovado', 'cancelado', 'pendente')
    );
GO
ALTER TABLE TB_PAYMENTS
ADD CONSTRAINT CHK_PAYMENTS_METHOD CHECK (
        PAYMENT_METHOD IN ('crédito', 'débito', 'boleto', 'pix')
    )
GO

ALTER TABLE TB_PAYMENTS
ADD CONSTRAINT CK_INSTALLMENT_TOTAL
CHECK (
    (INSTALLMENT_AMOUNT IS NULL OR INSTALLMENT IS NULL OR VALUE_PAID IS NULL)
    OR
    (INSTALLMENT_AMOUNT * INSTALLMENT <= VALUE_PAID)
)
GO

-- Constraints Viajantes

ALTER TABLE TB_TRAVELERS
ADD CONSTRAINT CK_EMAIL CHECK (EMAIL LIKE '%@%.com')
GO

ALTER TABLE TB_TRAVELERS
ADD CONSTRAINT CK_CPF_LENGTH CHECK (LEN(CPF) = 14) -- checa se tem 11 caracteres, mas não ignora o formato
GO
    
ALTER TABLE TB_TRAVELERS
ADD CONSTRAINT CK_CPF_FORMAT CHECK (
    CPF LIKE '[0-9][0-9][0-9].[0-9][0-9][0-9].[0-9][0-9][0-9]-[0-9][0-9]'
)
GO