-- Foreing Keys
-- TB RATINGS
ALTER TABLE TB_RATINGS
ADD CONSTRAINT FK_TB_RATINGS_ID_RESERVE FOREIGN KEY (ID_RESERVE) REFERENCES TB_RESERVATIONS(ID) ON DELETE CASCADE ON UPDATE CASCADE
GO 

-- TB_MEDIAS
ALTER TABLE TB_MEDIAS
ADD CONSTRAINT FK_TB_MEDIAS_PACKAGE_ID FOREIGN KEY (PACKAGE_ID) REFERENCES TB_PACKAGES(ID) ON DELETE CASCADE ON UPDATE CASCADE
GO 

-- TB_RESERVATIONS
ALTER TABLE TB_RESERVATIONS
ADD CONSTRAINT FK_USER_RESERVATIONS FOREIGN KEY (ID_USER) REFERENCES TB_USERS(ID)
GO

ALTER TABLE TB_RESERVATIONS
ADD CONSTRAINT FK_PACKAGES_RESERVATIONS FOREIGN KEY (ID_PACKAGES_DATES) REFERENCES TB_PACKAGES_DATES(ID)
GO 

-- TB_PAYMENTS
ALTER TABLE TB_PAYMENTS
ADD ID_RESERVATION UNIQUEIDENTIFIER;
GO
ALTER TABLE TB_PAYMENTS
ADD CONSTRAINT FK_PAYMENTS_RESERVATION FOREIGN KEY (ID_RESERVATION) REFERENCES TB_RESERVATIONS(ID);
GO

-- TB_TRAVELERS
ALTER TABLE TB_TRAVELERS
ADD ID_RESERVATION UNIQUEIDENTIFIER;
GO
ALTER TABLE TB_TRAVELERS
ADD CONSTRAINT FK_TRAVELERS_RESERVATIONS FOREIGN KEY (ID_RESERVATION) REFERENCES TB_RESERVATIONS(ID);
GO

-- FOREIGN KEY: TB_PACKAGES_DATES -> TB_PACKAGES
ALTER TABLE TB_PACKAGES_DATES
ADD CONSTRAINT FK_PACKAGES_DATES_PACKAGE
FOREIGN KEY (ID_PACKAGE) REFERENCES TB_PACKAGES(ID)
GO


-- �ndices para colunas de chave estrangeira

-- TB_RATINGS: �ndice para ID_RESERVE (chave estrangeira para TB_RESERVATIONS)
CREATE INDEX IDX_TB_RATINGS_ID_RESERVE ON TB_RATINGS(ID_RESERVE);
GO 

-- TB_MEDIAS: �ndice para PACKAGE_ID (chave estrangeira para TB_PACKAGES)
CREATE INDEX IDX_TB_MEDIAS_PACKAGE_ID ON TB_MEDIAS(PACKAGE_ID);
GO 

-- TB_RESERVATIONS: �ndice para ID_USER (chave estrangeira para TB_USERS)
CREATE INDEX IDX_TB_RESERVATIONS_ID_USER ON TB_RESERVATIONS(ID_USER);
GO

CREATE INDEX IDX_TB_RESERVATIONS_ID_PACKAGES_DATES ON TB_RESERVATIONS(ID_PACKAGES_DATES);
GO 

-- TB_PAYMENTS: �ndice para ID_RESERVATION (chave estrangeira para TB_RESERVATIONS)
CREATE INDEX IDX_TB_PAYMENTS_ID_RESERVATION ON TB_PAYMENTS(ID_RESERVATION);
GO 

-- TB_TRAVELERS: �ndice para ID_RESERVA (chave estrangeira para TB_RESERVA)
CREATE INDEX IDX_TB_TRAVELERS_ID_RESERVA ON TB_TRAVELERS(ID_RESERVATION);
GO